### ISSUE TITLE
Model Verification

### ISSUE THREAD

**Issue by magijoylarin** [wilselby/ROS_quadrotor_simulator#26]
Hi Please help me. I'm new to ROS and Gazebo and I followed your model verification directions but I wasn't able to create the URDF description. This is what I got:

~/ros/catkin_ws/src/ROS_quadrotor_simulator/quad_description/urdf$ rosrun xacro xacro.py kit_c.xacro -o /tmp/kit_c.urdfTraceback (most recent call last):
  File "/opt/ros/indigo/share/xacro/xacro.py", line 62, in <module>
    xacro.main()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 687, in main
    process_includes(doc, os.path.dirname(args[0]))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 246, in process_includes
    filename_spec = eval_text(elt.getAttribute('filename'), {})
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 485, in eval_text
    results.append(handle_extension(lex.next()[1][2:-1]))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 473, in handle_extension
    return eval_extension("$(%s)" % s)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 66, in eval_extension
    return substitution_args.resolve_args(str, context=substitution_args_context, resolve_anon=False)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 316, in resolve_args
    resolved = _resolve_args(resolved, context, resolve_anon, commands)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 329, in _resolve_args
    resolved = commands[command](resolved, a, args, context)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 157, in _find
    pkg_path = rp.get_path(args[0])
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 203, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
rospkg.common.ResourceNotFound: quad_description
ROS path [0]=/opt/ros/indigo/share/ros
ROS path [1]=/home/magi/ros/catkin_ws/src
ROS path [2]=/opt/ros/indigo/share
ROS path [3]=/opt/ros/indigo/stacks

**Comment by wilselby** [comment]
Make sure you run source /opt/ros/indigo/setup.bash

**Comment by magijoylarin** [comment]
Yes I did. Can you please help me find a way out this problem?
